# workflow using one AAD service principal for both ACR and AKV
name: test-notation-action-with-sp

on:
  push:
    branches:
      - main

env:
  ACR_TO_RELEASE: testnotation.azurecr.io
  ACR_REPO1_TO_RELEASE: gha1
  ACR_REPO2_TO_RELEASE: gha2
  KEY_ID: https://testnotationakv.vault.azure.net/keys/notation/570eae8ed8b44f1b8d6f187923b68a76
  NOTATION_EXPERIMENTAL: 1

jobs:
  # build and push the release, setup notation, sign the artifact, and 
  # verify the signature
  notation-setup-sign-verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: prepare
        id: prepare
        run: |
          TAG=sp
          echo "target_artifact_reference1=${{ env.ACR_TO_RELEASE }}/${{ env.ACR_REPO1_TO_RELEASE }}:${TAG}" >> "$GITHUB_ENV"
          echo "target_artifact_reference2=${{ env.ACR_TO_RELEASE }}/${{ env.ACR_REPO2_TO_RELEASE }}:${TAG}" >> "$GITHUB_ENV"
      - name: Azure login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_SP }}
      - name: ACR login
        run: |
            az acr login --name ${{ env.ACR_TO_RELEASE }}
      - name: Build and push
        id: push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.target_artifact_reference1 }}
            ${{ env.target_artifact_reference2 }}
      - name: Retrieve digest
        run: |
          echo "target_artifact_reference1=${{ env.ACR_TO_RELEASE }}/${{ env.ACR_REPO1_TO_RELEASE }}@${{ steps.push.outputs.digest }}" >> "$GITHUB_ENV"
          echo "target_artifact_reference2=${{ env.ACR_TO_RELEASE }}/${{ env.ACR_REPO2_TO_RELEASE }}@${{ steps.push.outputs.digest }}" >> "$GITHUB_ENV"
      - name: setup notation
        # this is equivalent to `uses: notaryproject/notation-action/setup@v1`
        uses: notaryproject/notation-action@main
      - name: sign released artifacts using key pair from AKV
        uses: notaryproject/notation-action/sign@main
        with:
          plugin_name: azure-kv
          plugin_url: https://github.com/Azure/notation-azure-kv/releases/download/v1.2.0/notation-azure-kv_1.2.0_linux_amd64.tar.gz
          plugin_checksum: 06bb5198af31ce11b08c4557ae4c2cbfb09878dfa6b637b7407ebc2d57b87b34
          key_id: ${{ env.KEY_ID }}
          target_artifact_reference: |-
            ${{ env.target_artifact_reference1 }}
            ${{ env.target_artifact_reference2 }}
          signature_format: cose
          plugin_config: |-
            ca_certs=.github/cert-bundle/cert-bundle.crt
            self_signed=false
          allow_referrers_api: 'true'
      - name: verify released artifacts
        uses: notaryproject/notation-action/verify@main
        with:
          target_artifact_reference: |-
            ${{ env.target_artifact_reference1 }}
            ${{ env.target_artifact_reference2 }}
          trust_policy: .github/trustpolicy/trustpolicy.json
          trust_store: .github/truststore
          allow_referrers_api: 'true'
